version: '3.1'

services:

  db:
    container_name: postgres
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: tutorials
    ports:
      - 5432:5432